# Generated by Django 4.2 on 2026-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
