# Generated by Django 4.2 on 2026-07-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='suppliers.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
