# Generated by Django 4.2 on 2026-07-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_supplier_delete_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='buying_price',
        ),
    ]
