# Generated by Django 4.2 on 2026-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_payment_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=20),
        ),
    ]
